apiVersion: v1
stringData:
  password: <path:secret/data/apps/wazuh#dashboard_password>
  username: <path:secret/data/apps/wazuh#dashboard_user>
kind: Secret
metadata:
  name: dashboard-cred
  namespace: wazuh
type: Opaque
---
apiVersion: v1
stringData:
  password: <path:secret/data/apps/wazuh#indexer_password>
  username: <path:secret/data/apps/wazuh#indexer_user>
kind: Secret
metadata:
  name: indexer-cred
  namespace: wazuh
type: Opaque
---
apiVersion: v1
stringData:
  password: <path:secret/data/apps/wazuh#api_password>
  username: <path:secret/data/apps/wazuh#api_user>
kind: Secret
metadata:
  name: wazuh-api-cred
  namespace: wazuh
type: Opaque
---
apiVersion: v1
stringData:
  authd.pass: <path:secret/data/apps/wazuh#authd_password>
kind: Secret
metadata:
  name: wazuh-authd-pass
  namespace: wazuh
type: Opaque
---
apiVersion: v1
stringData:
  key: <path:secret/data/apps/wazuh#cluster_key>
kind: Secret
metadata:
  name: wazuh-cluster-key
  namespace: wazuh
type: Opaque
