apiVersion: v1
kind: Service
metadata:
  labels:
    app: wazuh-manager
  name: wazuh-cluster
  namespace: wazuh
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: cluster
    port: 1516
    protocol: TCP
    targetPort: 1516
  selector:
    app: wazuh-manager
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wazuh-indexer
  name: wazuh-indexer
  namespace: wazuh
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: indexer-nodes
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: wazuh-indexer
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wazuh-dashboard
  name: dashboard
  namespace: wazuh
spec:
  ports:
  - name: dashboard
    port: 443
    protocol: TCP
    targetPort: 5601
  selector:
    app: wazuh-dashboard
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wazuh-manager
  name: wazuh
  namespace: wazuh
spec:
  ports:
  - name: api
    port: 55000
    protocol: TCP
    targetPort: 55000
  - name: registration
    port: 1515
    protocol: TCP
    targetPort: 1515
  selector:
    app: wazuh-manager
    node-type: conductor
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.io/ip-allocated-from-pool: first-pool
  labels:
    app: wazuh-manager
  name: wazuh-workers
  namespace: wazuh
spec:
  ports:
  - name: agents-events
    port: 1514
    protocol: TCP
    targetPort: 1514
  selector:
    app: wazuh-manager
    node-type: worker
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wazuh-indexer
  name: indexer
  namespace: wazuh
spec:
  ports:
  - name: indexer-rest
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: wazuh-indexer
  type: ClusterIP
